// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYtNzLw8c4OLl5yXskYK_sy0cn0xvWbA4',
    appId: '1:49247984675:web:2f157a6013eb67e61aa596',
    messagingSenderId: '49247984675',
    projectId: 'mobile-app-1d51b',
    authDomain: 'mobile-app-1d51b.firebaseapp.com',
    storageBucket: 'mobile-app-1d51b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4p4E0AKxvvs-cEtsqqFjlI2zENaUan_I',
    appId: '1:49247984675:android:54d3d4c4e15204e21aa596',
    messagingSenderId: '49247984675',
    projectId: 'mobile-app-1d51b',
    storageBucket: 'mobile-app-1d51b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI2JGkiqyYPtiYkXjRXrUOeqFroue_dcE',
    appId: '1:49247984675:ios:73a9ffbe174fee881aa596',
    messagingSenderId: '49247984675',
    projectId: 'mobile-app-1d51b',
    storageBucket: 'mobile-app-1d51b.appspot.com',
    iosBundleId: 'com.example.mc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI2JGkiqyYPtiYkXjRXrUOeqFroue_dcE',
    appId: '1:49247984675:ios:73a9ffbe174fee881aa596',
    messagingSenderId: '49247984675',
    projectId: 'mobile-app-1d51b',
    storageBucket: 'mobile-app-1d51b.appspot.com',
    iosBundleId: 'com.example.mc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYtNzLw8c4OLl5yXskYK_sy0cn0xvWbA4',
    appId: '1:49247984675:web:b2aba4705adffeaf1aa596',
    messagingSenderId: '49247984675',
    projectId: 'mobile-app-1d51b',
    authDomain: 'mobile-app-1d51b.firebaseapp.com',
    storageBucket: 'mobile-app-1d51b.appspot.com',
  );
}
